name: CI with Self-hosted Runner

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: self-hosted  # Use the self-hosted runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js (example, you can use other environments)
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: |
        npm install

    - name: Run tests
      run: |
        npm test

    - name: Clean up
      run: |
        echo "Cleaning up the workspace after tests"
